review_goals:
  - Ensure IBAN validation logic is robust and standards-compliant
  - Enforce accessibility (WCAG 2.1 AA and European Accessibility Act)
  - Prevent inline scripting, unsafe patterns, and CSP violations
  - Catch visual layout issues across screen sizes (mobile-first)
  - Ensure semantic HTML and proper ARIA usage
  - Detect performance bottlenecks in client-side JS
  - Promote consistent and maintainable CSS (variables, structure)
  - Encourage modular, reusable JavaScript components
  - Flag unused code or dependencies
  - Validate clear, user-friendly error messages and labels
language: en
codebase_type: frontend
